<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ArcForges.Contracts.PublicApi" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Grpc.Net.Client.Web" />
  </ItemGroup>
</Project>
